name: CI / CD - Deployment

on:
  push:
    branches: [ "prod" ]
  workflow_dispatch:

jobs:
  Checkout:
    runs-on: ubuntu-latest
    concurrency: ci-${{github.ref}}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

  Static_Analysis:
    needs: Checkout

    permissions:
      pages: write
      id-token: write

    environment:
      name: Homolog
      url: ${{ steps.deployment.outputs.page_url }}
    
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up node.js
        uses: actions/setup-node@v3.3.0
        with:
          node-version: '14'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Tests
        run: npm run test:prod

      - uses: actions/upload-artifact@v2
        with:
          name: analysis
          path: /home/runner/work/the-force/the-force/package.json

  Upload_Artifact:
    needs: Static_Analysis
    
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions/download-artifact@v2
        with:
          name: analysist

      - name: Build
        run: npm run build:prod

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: 'dist/the-force'

  Deploy:
    needs: Upload_Artifact

    permissions:
      pages: write
      id-token: write

    environment:
      name: Production
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Setup Pages
        uses: actions/configure-pages@v1
          
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
